name: Deploy to S3 Production

on:
  push:
    branches:
      - main  # Dispara quando há push na branch main
  workflow_dispatch:  # Permite execução manual

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://monfily-website --delete --cache-control "public, max-age=31536000" --exclude "*.html"
          aws s3 sync dist/ s3://monfily-website --delete --cache-control "public, max-age=300" --include "*.html"
          
      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id E30J3RSITMM0BL --paths "/*"
          
      - name: Deployment Success
        run: |
          echo "🚀 Deploy realizado com sucesso!"
          echo "📦 Arquivos sincronizados com S3"
          echo "🔄 Cache do CloudFront invalidado"